In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 문제1.

In [3]:
Month=[31,28,31,30,31,30,31,31,30,31,30,31]
M=int(input('Month :'))
print(Month[M-1])

Month :12
31


# 문제2.

In [4]:
Month=[31,28,31,30,31,30,31,31,30,31,30,31]
Day=0
while 1:
    M=int(input('Month :'))
    if M>=1 and M<=12:
        break
while(1):
    D=int(input('Day :'))
    if D>=1 and D<=Month[M-1]:
        break
for i in range(0,M-1):
    Day+=Month[i]
Day+=D
print(Day)

Month :12
Day :31
365


# 문제3.

In [5]:
while 1:
    k=int(input())
    if k==0:
        break
    elif k<10 or k>100:
        continue
    else:
        a=np.random.randint(1,10,size=(k))
        print(a)
        print('평균 : ',a.mean())
        print('분산 : ',a.var())
        print('표준편차 : ',a.std())

10
[7 1 6 5 3 1 7 1 2 7]
평균 :  4.0
분산 :  6.4
표준편차 :  2.5298221281347035
20
[8 9 3 2 4 5 8 7 5 4 7 5 7 7 6 4 4 2 5 8]
평균 :  5.5
분산 :  4.05
표준편차 :  2.0124611797498106
1000
0


# 문제4.

In [6]:
a=np.random.normal(80,15,size=(10,7))
a

array([[ 61.82318439, 103.8036098 ,  64.30483124,  85.55581883,
         90.65840988,  75.62940578,  69.48008039],
       [ 67.24912873,  89.0696944 ,  65.6441665 ,  68.01491895,
         72.63093835,  85.38879084,  72.60344332],
       [ 75.72623991,  98.66902595, 117.59605583, 113.73612989,
         84.41008529, 111.70070306,  90.2583932 ],
       [ 43.26460592,  88.42275142,  86.55829775,  89.97668448,
        109.85977859,  77.16386014,  96.41472625],
       [105.23784608,  82.12973324,  93.41231489,  76.94326836,
         83.26715333,  88.39474219,  75.96493718],
       [111.53260386,  67.3184067 ,  69.536443  ,  78.30436067,
         95.96972803,  62.15937356,  73.49905111],
       [ 85.7146929 , 121.98751314,  63.79904028,  84.822845  ,
         79.96885927,  70.21138977,  60.23143666],
       [107.53175385,  86.78427907,  85.50674375,  93.33735626,
         80.06453363,  91.86796297,  73.73726632],
       [ 98.46008249,  55.35204528,  82.03624062,  70.66589706,
         54.7812

In [7]:
print(a.max(0))
print(a.argmax(0))
for i in range(7):
    print('%d열 최대값: %f, 위치: %d행'%(i+1,a.max(0)[i],a.argmax(0)[i]+1))
print('\n')
for i in range(10):
    print('%d행 최대값: %f, 위치: %d열'%(i+1,a.max(1)[i],a.argmax(1)[i]+1))
    

[111.53260386 121.98751314 117.59605583 113.73612989 109.85977859
 111.70070306  96.41472625]
[5 6 2 2 3 2 3]
1열 최대값: 111.532604, 위치: 6행
2열 최대값: 121.987513, 위치: 7행
3열 최대값: 117.596056, 위치: 3행
4열 최대값: 113.736130, 위치: 3행
5열 최대값: 109.859779, 위치: 4행
6열 최대값: 111.700703, 위치: 3행
7열 최대값: 96.414726, 위치: 4행


1행 최대값: 103.803610, 위치: 2열
2행 최대값: 89.069694, 위치: 2열
3행 최대값: 117.596056, 위치: 3열
4행 최대값: 109.859779, 위치: 5열
5행 최대값: 105.237846, 위치: 1열
6행 최대값: 111.532604, 위치: 1열
7행 최대값: 121.987513, 위치: 2열
8행 최대값: 107.531754, 위치: 1열
9행 최대값: 98.460082, 위치: 1열
10행 최대값: 105.584572, 위치: 3열


# 문제5

In [8]:
a=np.random.randint(1,10,size=(12,5))
a

array([[5, 9, 6, 9, 2],
       [8, 7, 4, 5, 4],
       [4, 8, 8, 3, 1],
       [2, 2, 3, 2, 6],
       [6, 2, 1, 7, 6],
       [6, 4, 7, 7, 5],
       [9, 4, 3, 4, 2],
       [7, 2, 3, 7, 3],
       [9, 5, 9, 1, 5],
       [7, 1, 2, 3, 4],
       [2, 8, 8, 7, 7],
       [1, 5, 5, 1, 6]])

In [9]:
t, n = np.unique(a,return_counts=True)
for i in range(len(t)):
    print('데이터: %d, 개수: %d 개'%(t[i],n[i]))
print('\n')
for i in range(5):
    print('%d열 최솟값: %d, 위치: %d행'%(i+1,a.min(0)[i],a.argmin(0)[i]+1))

데이터: 1, 개수: 6 개
데이터: 2, 개수: 9 개
데이터: 3, 개수: 6 개
데이터: 4, 개수: 7 개
데이터: 5, 개수: 7 개
데이터: 6, 개수: 6 개
데이터: 7, 개수: 9 개
데이터: 8, 개수: 5 개
데이터: 9, 개수: 5 개


1열 최솟값: 1, 위치: 12행
2열 최솟값: 1, 위치: 10행
3열 최솟값: 1, 위치: 5행
4열 최솟값: 1, 위치: 9행
5열 최솟값: 1, 위치: 3행
